project:
  type: website
  render:
    - "*.qmd"

website:
  title: "slides"
  navbar:
    left:
      - href: confidence_slides.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



