project:
  type: website

website:
  title: "slides"
  navbar:
    left:
      - href: confidence_intervals.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



